version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y php8.1 php8.1-cli php8.1-common php8.1-mysql php8.1-zip php8.1-gd php8.1-mbstring php8.1-curl php8.1-xml php8.1-bcmath
      - php -v
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer --version
  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - composer install --no-dev --no-interaction --prefer-dist
  build:
    commands:
      - echo "Making scripts executable..."
      - chmod +x scripts/*.sh
      - echo "Packaging application..."
      - zip -r application.zip .
artifacts:
  files:
    - application.zip
    - appspec.yml
    - scripts/*
  discard-paths: no
