version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing dependencies..."
      - php -v
      - yum install -y php81 php81-cli php81-common php81-json php81-process php81-xml php81-mysqlnd php81-zip php81-gd php81-mbstring
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer --version
  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - composer install --no-dev --no-interaction --prefer-dist
  build:
    commands:
      - echo "Making scripts executable..."
      - chmod +x scripts/*.sh
      - echo "Packaging application..."
      - zip -r application.zip .
artifacts:
  files:
    - application.zip
    - appspec.yml
    - scripts/*
  discard-paths: no
