version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y zip unzip
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install
  build:
    commands:
      - echo "Making scripts executable..."
      - chmod +x scripts/*.sh
      - echo "Packaging application..."
      - zip -r application.zip .
artifacts:
  files:
    - application.zip
    - appspec.yml
    - scripts/*
  discard-paths: no
