version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing dependencies..."
      - amazon-linux-extras enable php8.1
      - yum clean metadata
      - yum install -y php-cli php-common php-json php-process php-xml php-mysqlnd php-zip php-gd php-mbstring
      - php -v
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer --version
  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - composer install --no-dev --no-interaction --prefer-dist
  build:
    commands:
      - echo "Making scripts executable..."
      - chmod +x scripts/*.sh
      - echo "Packaging application..."
      - zip -r application.zip .
artifacts:
  files:
    - application.zip
    - appspec.yml
    - scripts/*
  discard-paths: no
